; unified configuration file for outlook_daq.py and imap_daq.py
; this file can live in the same directory as the script being configured
; (e.g. outlook_daq.py or imap_daq.py) or %APPDATA% under Windows
; or under $HOME/.config under Linux
; Stop Forwarding and Start POSTing!
;
[credentials]
api_key = "YOUR_EMPIRASIGN_API_KEY"
api_secret = "YOUR_EMPIRASIGN_API_SECRET"

[outlook_settings]
auto_open_outlook = True
default_lookback_period = 1 ; upon restart only look back one day in history

; submit_category = _mkt_data
; after transmission, category will be prepended with an additional underscore
; i.e. messages that have been submitted will be __mkt_data category

[imap_settings]
imap_server = "imap.gmail.com" ; the imap server behind your email
; for gmail specifically, don't forget to enable IMAP in account setting
; and "less secure apps" in Gmail settings
email_account = "" ; insert email 'youremail@provider.com'
password = "" ; insert email password here
; source_folder = INBOX ; the name of the folder to scan
; completed_folder = PARSED ; the name of the folder to move submitted emails to

[user_settings]
business_hours_start = 7  ; start at 7am
business_hours_end = 17   ; stop at 5pm
business_hours_interval = 300 ; redo scan for new messages every 300 seconds
non_business_hours_interval = 1800  ; redo scan outside of business hours every 1800 seconds

[app_settings]
; probably don't mess around here unless you know what you're doing
; or you've been advised by Empirasign personnel

; proxy_server = ""
; If you need to locate your proxy server, the easiest way to do this is by
; using our tool on the "proxy_finder" tab the of demo api spreadsheet,
; Click the "Find Proxy" button, results will show up in cell B4
; demo api spreadsheet can be found at:
; https://www.empirasign.com/api-mbs/  click on Excel icon to download

; for testing and debugging your own code, you may set
; debug = True
; debug_url = https://enu05nqryoyp.x.pipedream.net
; via https://requestbin.com/

; log_dir =
